# TODO: Get dictionaries
# TODO: Get translations

name: Build psi+

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  update:
    name: Update eth0fox/psi from patches
    runs-on: ubuntu-latest
    steps:
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"

      - name: Checkout (this) repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: builds
      - name: Checkout psi repository
        uses: actions/checkout@v3
        with:
          repository: eth0fox/psi
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
          path: psi
      - name: Add upstream remote
        working-directory: psi
        run: |
          git remote add upstream https://github.com/psi-im/psi.git
          git fetch upstream
      - name: Apply & push patches
        working-directory: psi
        run: |
          for patchset in ../builds/patchsets/*; do
            echo ""
            echo "- Applying patchset: $patchset -"
            branch_name=$(basename "$patchset")
            git checkout -B "$branch_name" upstream/master
            git am "$patchset"/*.patch
            git push origin "$branch_name" --force
          done

          # Reset master and merge in the patch branches
          echo ""
          echo " == Merging patch branches into master =="
          echo ""
          git checkout -B master upstream/master
          for patchset in ../builds/patchsets/*; do
            echo ""
            echo "- Merging patchset: $patchset -"
            branch_name=$(basename "$patchset")
            git merge --no-ff "$branch_name" -m "Merge $branch_name"
            git push origin master --force
          done

  snapshot:
    name: Build psi+ snapshot
    runs-on: ubuntu-latest
    needs: update
    steps:
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
      - name: Checkout psi+ repository
        uses: actions/checkout@v3
        with:
          repository: psi-plus/psi-plus-snapshots
          fetch-depth: 1
          path: psi-plus-snapshots
      - name: Patch script
        working-directory: psi-plus-snapshots
        run: |
          sed -i "s/https:\/\/github.com\/psi-im\/psi.git/https:\/\/github.com\/eth0fox\/psi.git/g" generate-single-repo.sh
          sed -i "s/https:\/\/github.com\/psi-plus\/psi-plus-snapshots.git/https:\/\/github.com\/psi-plus\/psi-plus-snapshots/g" generate-single-repo.sh
          sed -i "s/NEW_VER=\"[^\"]*\"/NEW_VER=\"\${PSI_NEW_HASH}\"/g" generate-single-repo.sh
      - name: Generate snapshot
        working-directory: psi-plus-snapshots
        run: |
          ./generate-single-repo.sh

      - name: Create tarball
        run: |
          tar -czf psi-plus-snapshot.tar.gz psi-plus-snapshots
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: psi-plus-snapshot
          path: psi-plus-snapshot.tar.gz

  build_mac_x86:
    name: Build psi+ for macOS x86_64
    runs-on: macos-26-intel
    needs: snapshot
    steps:
      - name: Install dependencies
        run: |
          brew install ccache coreutils cmake hunspell minizip qt@5 qtkeychain tidy-html5 libotr libomemo-c gnupg pinentry-mac wget 
      - name: Download source snapshot
        uses: actions/download-artifact@v5
        with:
          name: psi-plus-snapshot
      - name: Extract source snapshot
        run: |
          tar -xzf psi-plus-snapshot.tar.gz
          ls

      
      - name: Hope for the best
        working-directory: psi-plus-snapshots
        run: |
          ./mac/build-using-homebrew.sh
      
      - name: Move artifact
        run: |
          mv Psi*.dmg psi-plus-mac-x86_64.dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: psi-plus-mac-x86_64
          path: psi-plus-mac-x86_64.dmg


